### PR TITLE
updated docs and put ox and oy

### PR DESCRIPTION
**Pull request by flamendless**

### CODE REVIEW

**Comment by josh-perry** [comment]
This has already been done?

**Comment by flamendless** [comment]
There wasnt an ox and oy parameter.

**Comment by josh-perry** [comment]
I've merged in #10 which had your 7e90a90795a3750b4db00b8c3f74efd14425e495 commit, though

**Comment by flamendless** [comment]
Well ive just checked the master branch, the ox and oy wasnt merged.

**Comment by josh-perry** [comment]
https://github.com/josh-perry/peachy/blob/master/peachy.lua#L138

**Comment by flamendless** [comment]
Ohh. Hmm weird. Okay I'll close this pr

**Pull request closed without merging**
